Repository reviewpad/reviewpad, pull requests merged in 2022-07, with the labels that each got.

#41 Update reviewpad action to v3.x
  .github/workflows/reviewpad.yml
  reviewpad.yml
Labels: small

#40 Add unit tests for `$merge` action builtin
  plugins/aladino/actions/merge.go
  plugins/aladino/actions/merge_test.go
Labels: large

#43 Add unit tests for `$comment` action builtin
  plugins/aladino/actions/comment_test.go
Labels: medium

#53 Add unit test for utils file
  utils/file_test.go
Labels: small

#54 Add unit tests for utils fmtio
  utils/fmtio/errors_test.go
  utils/fmtio/logs_test.go
  utils/fmtio/prints_test.go
Labels: medium

#55 Add unit tests for utils report `Error`
  utils/report/error_test.go
Labels: small

#35 Substitute PR request for PR requested reviewers request in `$assignRandomReviewer` action builtin
  plugins/aladino/actions/assignRandomReviewer.go
  utils/github.go
Labels: medium, small

#42 Add unit tests for `$removeLabel` action builtin
  go.mod
  mocks/aladino/mocks.go
  plugins/aladino/actions/removeLabel.go
  plugins/aladino/actions/removeLabel_test.go
Labels: large

#45 Add unit tests for `$close` action builtin
  plugins/aladino/actions/close_test.go
Labels: medium

#57 fix error handling
  runner.go
Labels: external-contribution

#74 [ship]: Add template for pull requests
  .github/PULL_REQUEST_TEMPLATE/general.md
Labels: ship, small

#50 Add unit tests for utils array
  utils/array_test.go
Labels: medium

#75 [ship]: Add editorconfig
  .editorconfig
  README.md
Labels: ship, medium

#80 [ship]: Add spaces to fix format in Architecture section
  README.md
Labels: ship, small

#64 Add unit tests for pull request ident gets in utils github
  utils/github_test.go
Labels: medium, large, run-build

#73 Add unit tests for `$assignees` function builtin
  plugins/aladino/functions/assignees_test.go
Labels: plugins, medium, run-build

#76 Add unit tests for `$author` function builtin
  plugins/aladino/functions/author_test.go
Labels: plugins, medium, run-build

#79 Add unit tests for `$commits` function builtin
  plugins/aladino/functions/commits.go
  plugins/aladino/functions/commits_test.go
  utils/github.go
Labels: plugins, large, run-build

#82 Add unit tests for `$description` function builtin
  plugins/aladino/functions/description_test.go
Labels: plugins, medium, run-build

#81 Add unit tests for `$createdAt` function builtin
  plugins/aladino/functions/createdAt_test.go
Labels: plugins, medium, run-build

#84 Add unit tests for `$group` function builtin
  plugins/aladino/functions/group_test.go
Labels: plugins, medium, run-build

#94 Add `$hasCodePattern` unit tests
  plugins/aladino/functions/hasCodePattern_test.go
Labels: plugins, medium, run-build

#95 Add `$hasFileExtensions` unit tests
  plugins/aladino/functions/hasFileExtensions_test.go
Labels: plugins, medium, run-build

#96 Add `$hasFileName` unit tests
  plugins/aladino/functions/hasFileName_test.go
Labels: plugins, medium, run-build

#97 Add `$hasFilePattern` unit tests
  plugins/aladino/functions/hasFilePattern_test.go
Labels: plugins, medium, run-build

#103 Add `$isElementOf` function unit tests
  plugins/aladino/functions/isElementOf_test.go
Labels: plugins, medium, run-build

#104 Add `$labels` function unit tests
  mocks/aladino/mocks.go
  plugins/aladino/functions/labels_test.go
Labels: plugins, medium, run-build

#105 Add `$milestone` function unit tests
  mocks/aladino/mocks.go
  plugins/aladino/functions/milestone_test.go
Labels: plugins, medium, run-build

#107 Add `$reviewers` function unit tests
  mocks/aladino/mocks.go
  plugins/aladino/functions/reviewers_test.go
Labels: plugins, medium, run-build

#108 Add `$rule` function unit tests
  plugins/aladino/functions/rule_test.go
Labels: plugins, medium, run-build

#109 Add `$size` function unit tests
  mocks/aladino/mocks.go
  plugins/aladino/functions/size_test.go
Labels: plugins, medium, run-build

#111 Add `$title` function unit tests
  mocks/aladino/mocks.go
  plugins/aladino/functions/title_test.go
Labels: plugins, medium, large, run-build

#98 Add `$hasLinearHistory` unit tests
  plugins/aladino/functions/hasLinearHistory_test.go
Labels: plugins, large, run-build

#101 Add `$isDraft` function unit tests
  mocks/aladino/mocks.go
  plugins/aladino/functions/isDraft.go
  plugins/aladino/functions/isDraft_test.go
Labels: plugins, medium, run-build

#106 Add `$organization` function unit tests
  plugins/aladino/functions/organization_test.go
Labels: plugins, medium, large, run-build

#113 Add unit tests for github paginated request functions
  utils/github_test.go
Labels: large, run-build

#115 Add unit tests for github `GetPullRequestFiles`
  utils/github_test.go
Labels: medium, run-build

#116 Add unit tests for github `GetPullRequestReviewers`
  utils/github_test.go
Labels: medium, run-build

#117 Add unit tests for github `GetRepoCollaborators`
  utils/github_test.go
Labels: medium, run-build

#121 test: github `GetPullRequestCommits` unit tests
  utils/github_test.go
Labels: medium, run-build

#128 feat: gitignore IntelliJ IDEA folder
  .gitignore
Labels: external-contribution, small, run-build

#123 test: aladino value unit tests
  lang/aladino/value_test.go
Labels: large, run-build

#127 test: unit test for `lang/aladino/builtins.go`
  lang/aladino/builtins_test.go
Labels: medium, run-build

#126 test: `filter` function builtin unit tests
  plugins/aladino/functions/filter_test.go
Labels: plugins, medium, run-build

#130 fix: yaml multiline, issue #89
  lang/aladino/parse.go
  lang/aladino/parse_test.go
Labels: plugins, medium, large, external-contribution, run-build

#151 fix: :bug: fix incorrect error messages in cli
  cmd/cli/main.go
Labels: external-contribution, small, run-build

#136 fix: not request review already approved pr
  plugins/aladino/actions/assignReviewer.go
  plugins/aladino/actions/assignReviewer_test.go
Labels: plugins, medium, large, external-contribution, small, run-build

#154 fix: :bug: dry runs shouldn't create labels on pull requests
  engine/env.go
  engine/exec.go
  runner.go
Labels: external-contribution, critical, small, run-build

#155 refactor: mocks aladino in same package
  lang/aladino/mocks.go
  plugins/aladino/actions/addLabel_test.go
  plugins/aladino/actions/assignAssignees_test.go
  plugins/aladino/actions/assignRandomReviewer_test.go
  plugins/aladino/actions/assignReviewer_test.go
  plugins/aladino/actions/assignTeamReviewer_test.go
  plugins/aladino/actions/close_test.go
  plugins/aladino/actions/commentOnce_test.go
  plugins/aladino/actions/comment_test.go
  plugins/aladino/actions/merge_test.go
  plugins/aladino/actions/removeLabel_test.go
  plugins/aladino/functions/appendString_test.go
  plugins/aladino/functions/assignees_test.go
  plugins/aladino/functions/author_test.go
  plugins/aladino/functions/base_test.go
  plugins/aladino/functions/commentCount_test.go
  plugins/aladino/functions/comments_test.go
  plugins/aladino/functions/commitCount_test.go
  plugins/aladino/functions/commits_test.go
  plugins/aladino/functions/contains_test.go
  plugins/aladino/functions/createdAt_test.go
  plugins/aladino/functions/description_test.go
  plugins/aladino/functions/fileCount_test.go
  plugins/aladino/functions/filter_test.go
  plugins/aladino/functions/group_test.go
  plugins/aladino/functions/hasCodePattern_test.go
  plugins/aladino/functions/hasFileExtensions_test.go
  plugins/aladino/functions/hasFileName_test.go
  plugins/aladino/functions/hasFilePattern_test.go
  plugins/aladino/functions/hasLinearHistory_test.go
  plugins/aladino/functions/hasLinkedIssues_test.go
  plugins/aladino/functions/head_test.go
  plugins/aladino/functions/isDraft_test.go
  plugins/aladino/functions/isElementOf_test.go
  plugins/aladino/functions/labels_test.go
  plugins/aladino/functions/milestone_test.go
  plugins/aladino/functions/organization_test.go
  plugins/aladino/functions/reviewers_test.go
  plugins/aladino/functions/rule_test.go
  plugins/aladino/functions/size_test.go
  plugins/aladino/functions/startsWith_test.go
  plugins/aladino/functions/team_test.go
  plugins/aladino/functions/title_test.go
  plugins/aladino/functions/totalCreatedPullRequests_test.go
  plugins/aladino/functions/workflowStatus_test.go
  utils/github_test.go
Labels: plugins, large, run-build

#131 test: lang aladino env unit tests
  lang/aladino/env_test.go
  lang/aladino/file.go
  lang/aladino/mocks.go
Labels: large, run-build

#133 test: add unit tests for lang/aladino eval
  lang/aladino/env_test.go
  lang/aladino/eval_test.go
  lang/aladino/mocks.go
Labels: large, run-build

#134 test: add unit tests for lang/aladino file
  lang/aladino/file_internal_test.go
Labels: medium, large, run-build

#135 test: add unit tests for lang/aladino exec
  lang/aladino/exec_internal_test.go
  lang/aladino/mocks.go
Labels: medium, large, run-build

#138 test: add unit tests for lang/aladino interpreter `ProcessGroup`
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
Labels: large, small, run-build

#140 test: add unit tests for lang/aladino interpreter `BuildInternalLabelID`
  lang/aladino/interpreter_internal_test.go
Labels: small, run-build

#141 test: add unit tests for lang/aladino interpreter `ProcessLabel`
  lang/aladino/interpreter_internal_test.go
Labels: medium, small, run-build

#142 test: add unit tests for lang/aladino interpreter `BuildInternalRuleName`
  lang/aladino/interpreter_internal_test.go
Labels: small, run-build

#143 test: add unit tests for lang/aladino interpreter `ProcessRule`
  lang/aladino/interpreter_internal_test.go
Labels: medium, small, run-build

#144 test: add unit tests for lang/aladino interpreter `EvalExpr`
  lang/aladino/interpreter_internal_test.go
Labels: medium, run-build

#145 test: add unit tests for lang/aladino interpreter `ExecProgram`
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
Labels: large, run-build

#146 test: add unit tests for lang/aladino interpreter `ExecStatement`
  lang/aladino/interpreter_internal_test.go
Labels: large, run-build

#147 test: add unit tests for lang/aladino interpreter `Report`
  lang/aladino/interpreter_internal_test.go
Labels: large, run-build

#148 test: add unit tests for lang/aladino interpreter `NewInterpreter`
  lang/aladino/interpreter_internal_test.go
Labels: medium, run-build

#161 build: check code coverage
  .github/workflows/build.yml
  .github/workflows/pull_request_build.yml
  .gitignore
  lang/aladino/parser.go
Labels: medium, large, run-build

#166 test: add unit tests for lang/aladino type
  lang/aladino/type.go
  lang/aladino/type_internal_test.go
Labels: large, run-build

#163 test: add unit tests for lang/aladino expr
  lang/aladino/expr_internal_test.go
Labels: large, run-build

#165 test: add unit tests for lang/aladino report
  lang/aladino/report_internal_test.go
Labels: large, run-build

#168 refactor: rename lang/aladino type unit tests
  lang/aladino/type_internal_test.go
Labels: medium, run-build

#169 chore: remove generated files from code coverage
  Taskfile.yml
  scripts/exclude-from-code-coverage.sh
  scripts/resources/exclude-from-code-coverage.txt
Labels: small, run-build

#173 test: add unit tests for engine program
  engine/program.go
  engine/program_internal_test.go
Labels: medium, run-build

#167 test: add unit tests for lang/aladino typeinfer
  lang/aladino/env.go
  lang/aladino/env_test.go
  lang/aladino/expr.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
  lang/aladino/typeinfer.go
  lang/aladino/typeinfer_internal_test.go
Labels: large, run-build

#171 test: add unit tests for engine env & mocks for engine
  engine/env_test.go
  engine/mocks.go
Labels: large, run-build

#172 test: add unit tests for engine lang
  engine/lang.go
  engine/lang_internal_test.go
  go.mod
  go.sum
Labels: large, run-build

#170 Add built-in utility function `$reviewerStatus`
  plugins/aladino/builtins.go
  plugins/aladino/functions/reviewerStatus.go
  plugins/aladino/functions/reviewerStatus_test.go
  utils/github.go
  utils/github_test.go
Labels: plugins, large, external-contribution, run-build

#182 [ship]: add GetPullRequests to utils/github
  plugins/aladino/functions/reviewerStatus.go
  utils/github.go
  utils/github_test.go
Labels: plugins, ship, medium, run-build

#183 fix: only exclude reviewers that have approved the pull request
  plugins/aladino/actions/assignReviewer.go
  plugins/aladino/actions/assignReviewer_test.go
Labels: plugins, medium, run-build

#158 feat: :sparkles: comment dry run report
  cmd/cli/main.go
  engine/env.go
  lang/aladino/env.go
  lang/aladino/env_test.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
  lang/aladino/report.go
  lang/aladino/report_internal_test.go
  runner.go
Labels: medium, large, external-contribution, critical, run-build

#188 [ship]: feat: add safe mode run as CLI argument
  cmd/cli/main.go
Labels: ship, small, run-build

#189 fix: use empty event when not provided on cli
  cmd/cli/main.go
Labels: small, run-build

#194 refactor: fail on mockEnvWith function instead of returning error
  lang/aladino/env_test.go
  lang/aladino/eval_test.go
  lang/aladino/exec_internal_test.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
  lang/aladino/report_internal_test.go
  lang/aladino/typeinfer_internal_test.go
  plugins/aladino/actions/addLabel_test.go
  plugins/aladino/actions/assignAssignees_test.go
  plugins/aladino/actions/assignRandomReviewer_test.go
  plugins/aladino/actions/assignReviewer_test.go
  plugins/aladino/actions/assignTeamReviewer_test.go
  plugins/aladino/actions/close_test.go
  plugins/aladino/actions/commentOnce_test.go
  plugins/aladino/actions/comment_test.go
  plugins/aladino/actions/merge_test.go
  plugins/aladino/actions/removeLabel_test.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/appendString_test.go
  plugins/aladino/functions/assignees_test.go
  plugins/aladino/functions/author_test.go
  plugins/aladino/functions/base_test.go
  plugins/aladino/functions/commentCount_test.go
  plugins/aladino/functions/comments_test.go
  plugins/aladino/functions/commitCount_test.go
  plugins/aladino/functions/commits_test.go
  plugins/aladino/functions/contains_test.go
  plugins/aladino/functions/createdAt_test.go
  plugins/aladino/functions/description_test.go
  plugins/aladino/functions/fileCount_test.go
  plugins/aladino/functions/filter_test.go
  plugins/aladino/functions/group_test.go
  plugins/aladino/functions/hasCodePattern_test.go
  plugins/aladino/functions/hasFileExtensions_test.go
  plugins/aladino/functions/hasFileName_test.go
  plugins/aladino/functions/hasFilePattern_test.go
  plugins/aladino/functions/hasLinearHistory_test.go
  plugins/aladino/functions/hasLinkedIssues_test.go
  plugins/aladino/functions/head_test.go
  plugins/aladino/functions/isDraft_test.go
  plugins/aladino/functions/isElementOf_test.go
  plugins/aladino/functions/labels_test.go
  plugins/aladino/functions/length_test.go
  plugins/aladino/functions/milestone_test.go
  plugins/aladino/functions/organization_test.go
  plugins/aladino/functions/reviewerStatus_test.go
  plugins/aladino/functions/reviewers_test.go
  plugins/aladino/functions/rule_test.go
  plugins/aladino/functions/size_test.go
  plugins/aladino/functions/startsWith_test.go
  plugins/aladino/functions/team_test.go
  plugins/aladino/functions/title_test.go
  plugins/aladino/functions/totalCreatedPullRequests_test.go
  plugins/aladino/functions/workflowStatus_test.go
  utils/github_test.go
Labels: plugins, large, run-build

#200 feat: $disableActions built-in
  lang/aladino/builtins.go
  lang/aladino/exec.go
  lang/aladino/exec_internal_test.go
  plugins/aladino/actions/disableActions.go
  plugins/aladino/actions/disableActions_test.go
  plugins/aladino/builtins.go
Labels: plugins, large, run-build

#202 [ship]: chore: improve action disable logging
  lang/aladino/exec.go
Labels: ship, small, run-build

#206 fix: check uses of rule built-in
  engine/linter.go
  engine/linter_internal_test.go
Labels: run-build
