Repository reviewpad/reviewpad, pull requests merged in 2022-06, with the labels that each got.

#3 Add $rule function builtin
  engine/env.go
  go.mod
  lang/aladino/interpreter.go
  lang/aladino/report.go
  plugins/aladino/builtins.go
  plugins/aladino/functions.go
Labels: plugins

#5 [ship]: Update README
  README.md
Labels: ship

#17 [ship]: Lint rule and group references
  engine/linter.go
Labels: ship

#18 [ship]: Update README
  README.md
Labels: ship

#20 [ship]: Update to major version v2
  cmd/cli/main.go
  engine/env.go
  engine/exec.go
  engine/labels.go
  engine/linter.go
  go.mod
  lang/aladino/diff.go
  lang/aladino/env.go
  lang/aladino/expr.go
  lang/aladino/interpreter.go
  lang/aladino/report.go
  plugins/aladino/actions.go
  plugins/aladino/builtins.go
  plugins/aladino/functions.go
  runner.go
Labels: ship

#24 Allow a comment only once in a pull request
  go.mod
  go.sum
  lang/aladino/env.go
  lang/aladino/report.go
  plugins/aladino/actions.go
  plugins/aladino/actions_test.go
  plugins/aladino/builtins.go
  plugins/aladino/mocks.go
  utils/github.go
Labels: plugins, large

#30 Add YAML property to define failure mode
  engine/lang.go
  engine/loader.go
Labels: medium

#27 Request the review of a set of teams
  plugins/aladino/actions.go
  plugins/aladino/actions_test.go
  plugins/aladino/builtins.go
Labels: plugins, medium, large

#25 Paginate list comments request in aladino report
  lang/aladino/report.go
  plugins/aladino/actions.go
  utils/github.go
Labels: plugins, small
