Repository reviewpad/reviewpad, pull requests merged in 2022-08, with the labels that each got.

#209 docs(README): add test information
  README.md
Labels: ship, small

#207 feat!: add reviewpad-cli
  .gitignore
  README.md
  Taskfile.yml
  cli/cmd/check.go
  cli/cmd/flags.go
  cli/cmd/root.go
  cli/cmd/run.go
  cli/main.go
  cli/testdata/test_complete_workflow_run_event.json
  cli/testdata/test_open_pr_event.json
  go.mod
  go.sum
Labels: large, run-build, ask

#198 feat: add builtin isWaitingForReview
  plugins/aladino/builtins.go
  plugins/aladino/functions/isWaitingForReview.go
  plugins/aladino/functions/isWaitingForReview_test.go
Labels: plugins, large, run-build, ask

#192 feat: remove mocks files from code coverage
  scripts/resources/exclude-from-code-coverage.txt
Labels: small, run-build, ask, waiting-review

#214 fix: change log message format for addLabel
  plugins/aladino/actions/addLabel.go
  plugins/aladino/actions/removeLabel.go
Labels: plugins, external-contribution, small, ask

#203 $addToProject built in action
  lang/aladino/mocks.go
  plugins/aladino/actions/addToProject.go
  plugins/aladino/actions/addToProject_test.go
  plugins/aladino/builtins.go
  utils/github_projects.go
  utils/github_projects_test.go
  utils/test.go
Labels: plugins, large, external-contribution, ask

#193 refactor: add builders to engine.Program
  engine/exec.go
  engine/program.go
  engine/program_internal_test.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/report.go
  lang/aladino/report_internal_test.go
Labels: large, ask

#224 fix: updated cli run command and flags in readme
  README.md
Labels: external-contribution, small

#230 feat: simplify report
  engine/env_test.go
  engine/exec.go
  engine/program.go
  engine/program_internal_test.go
  lang/aladino/env.go
  lang/aladino/env_test.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/report.go
  lang/aladino/report_internal_test.go
Labels: large, run-build, show

#174 test: add unit tests for engine loader
  engine/loader_test.go
  engine/testdata/loader/reviewpad_appended.yml
  engine/testdata/loader/reviewpad_with_cyclic_dependency_a.yml
  engine/testdata/loader/reviewpad_with_cyclic_dependency_b.yml
  engine/testdata/loader/reviewpad_with_import_file_with_parse_error.yml
  engine/testdata/loader/reviewpad_with_import_of_nonexistent_file.yml
  engine/testdata/loader/reviewpad_with_imports_chain.yml
  engine/testdata/loader/reviewpad_with_no_imports.yml
  engine/testdata/loader/reviewpad_with_one_import.yml
  engine/testdata/loader/reviewpad_with_parse_error.yml
  engine/testdata/loader/transform/reviewpad_after_action_transform.yml
  engine/testdata/loader/transform/reviewpad_after_extra_action_transform.yml
  engine/testdata/loader/transform/reviewpad_before_action_transform.yml
  engine/testdata/loader/transform/reviewpad_before_extra_action_transform.yml
  go.mod
  go.sum
Labels: large, run-build, ask

#180 test: add unit tests for engine exec
  engine/exec.go
  engine/exec_test.go
  engine/loader_test.go
  engine/mocks.go
  engine/testdata/exec/reviewpad_with_activated_workflow_with_extra_actions.yml
  engine/testdata/exec/reviewpad_with_invalid_group.yml
  engine/testdata/exec/reviewpad_with_invalid_workflow.yml
  engine/testdata/exec/reviewpad_with_multiple_activated_workflows.yml
  engine/testdata/exec/reviewpad_with_no_activated_workflows.yml
  engine/testdata/exec/reviewpad_with_one_activated_workflow.yml
  engine/testdata/exec/reviewpad_with_skipped_workflow.yml
  engine/testdata/exec/reviewpad_with_unnamed_label.yml
  engine/testdata/exec/reviewpad_with_valid_group.yml
  engine/testdata/exec/reviewpad_with_valid_label.yml
  engine/testutils/parse.go
  utils/load.go
Labels: large, run-build, ask

#219 feat!: store action built-ins messages by severity in environment
  engine/env.go
  lang/aladino/env.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  plugins/aladino/actions/fail.go
  runner.go
Labels: plugins, medium, critical, run-build, ask

#233 experimental: add pipelines
  engine/exec.go
  engine/lang.go
  engine/loader.go
  engine/loader_internal_test.go
Labels: large, run-build, ask

#245 feat: coverage difference
  Taskfile.yml
Labels: external-contribution, small, run-build, ask

#246 refactor!: builtin hasUnaddressedThreads
  plugins/aladino/builtins.go
  plugins/aladino/functions/hasUnaddressedThreads.go
  plugins/aladino/functions/hasUnaddressedThreads_test.go
Labels: plugins, medium, run-build, ask

#255 feat: add download contents to codehost
  codehost/github/repositories.go
Labels: ship, small, run-build

#225 feat: sprintf returns formated string
  plugins/aladino/builtins.go
  plugins/aladino/functions/sprintf.go
  plugins/aladino/functions/sprintf_test.go
Labels: plugins, medium, external-contribution, run-build, ask

#234 fix: addToProject fetches the wrong project
  codehost/github/projects.go
  codehost/github/projects_test.go
  plugins/aladino/actions/addToProject_test.go
Labels: plugins, medium, large, external-contribution, run-build, ask

#262 feat: add changed built-in
  plugins/aladino/builtins.go
  plugins/aladino/functions/changed.go
  plugins/aladino/functions/changed_test.go
Labels: plugins, large, run-build, show

#247 feat: add $commitLint action built-in
  go.mod
  go.sum
  lang/aladino/env.go
  plugins/aladino/actions/commitLint.go
  plugins/aladino/actions/commitLint_test.go
  plugins/aladino/builtins.go
Labels: plugins, large, run-build, ask

#251 feat: add $error action built-in
  plugins/aladino/actions/errorMsg.go
  plugins/aladino/actions/errorMsg_test.go
  plugins/aladino/builtins.go
Labels: plugins, medium, run-build, ask

#252 feat: add $warn built-in
  lang/aladino/env.go
  plugins/aladino/actions/commitLint_test.go
  plugins/aladino/actions/warn.go
  plugins/aladino/actions/warn_test.go
  plugins/aladino/builtins.go
Labels: plugins, medium, run-build, ask

#253 feat: add $info action built-in
  lang/aladino/env.go
  plugins/aladino/actions/commitLint_test.go
  plugins/aladino/actions/info.go
  plugins/aladino/actions/info_test.go
  plugins/aladino/builtins.go
Labels: plugins, medium, run-build, ask

#265 Update report generation for info, warn and error builtins
  lang/aladino/env.go
  lang/aladino/interpreter.go
  lang/aladino/report.go
  lang/aladino/report_internal_test.go
  plugins/aladino/actions/commitLint_test.go
Labels: run-build

#270 fix: semantic client connection
  go.mod
  go.sum
  plugins/aladino/builtins.go
  plugins/aladino/services/semantic.go
  runner.go
Labels: run-build

#256 feat: add $lastEventAt built-in
  codehost/github/pull_requests.go
  codehost/github/pull_requests_test.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/createdAt.go
  plugins/aladino/functions/lastEventAt.go
  plugins/aladino/functions/lastEventAt_test.go
Labels: plugins, large, run-build, ask

#273 feat(docs): add banner to README.md
  README.md
Labels: documentation, external-contribution, small, ask

#276 docs: update README.md
  README.md
Labels: ship, small

#282 feat: add GetDefaultRepositoryBranch
  codehost/github/repositories.go
Labels: ship, small, run-build

#280 fix: paginated request on next page processing
  codehost/github/pagination.go
Labels: small, run-build, ask

#285 feat: add on property to workflows
  engine/exec.go
  engine/lang.go
  engine/loader.go
  engine/loader_test.go
  engine/testdata/loader/transform/reviewpad_after_on_transform.yml
  engine/testdata/loader/transform/reviewpad_before_on_transform.yml
Labels: ship, medium, run-build

#291 feat: rule kind property is optional
  engine/loader.go
  engine/loader_test.go
  engine/testdata/loader/transform/reviewpad_after_kind_transform.yml
  engine/testdata/loader/transform/reviewpad_before_kind_transform.yml
Labels: ship, medium, run-build

#300 feat: extend cron event for issues and pull requests
  codehost/github/issues.go
  handler/processors.go
  handler/processors_test.go
Labels: ship, medium, run-build

#302 Link License File in ReadMe
  README.md
Labels: external-contribution, small, ask

#281 feat: validate pull request title with conventional commits
  plugins/aladino/actions/titleLint.go
  plugins/aladino/actions/titleLint_test.go
  plugins/aladino/builtins.go
Labels: plugins, large, external-contribution, run-build, ask, waiting-review

#316 feat: add to project support for issues
  codehost/github/projects_test.go
  lang/aladino/mocks.go
  plugins/aladino/actions/addToProject.go
  plugins/aladino/actions/addToProject_test.go
Labels: plugins, ship, medium, run-build

#317 chore: update ci build to use reviewpad ci container image
  .github/workflows/build.yml
  .github/workflows/pull_request_build.yml
  ci/baseimage/dockerfile
Labels: ship, medium, run-build

#254 feat: lambda function
  lang/aladino/lex.go
  lang/aladino/parse_test.go
  lang/aladino/parser.go
  lang/aladino/parser.y
Labels: large, external-contribution, run-build, ask, waiting-review

#260 feat: typed expression
  lang/aladino/lex.go
  lang/aladino/parse_test.go
  lang/aladino/parser.go
  lang/aladino/parser.y
Labels: large, external-contribution, run-build, ask, waiting-review

#323 fix: process issue comment separates between issue and pull request
  handler/processors.go
Labels: ship, small, run-build

#301 test: improve PaginatedRequest and ParseLink tests
  codehost/github/pull_requests_test.go
Labels: large, run-build, ask, waiting-review, requires-author-attention
