Repository reviewpad/reviewpad, pull requests merged in 2023-05, with the labels that each got.

#855 feat: assign reviewers command users $assignCodeAuthorReviewers built-in
  engine/commands/assignReviewer.go
  engine/commands/assignReviewer_test.go
  engine/exec_test.go
Labels: large, ask, requires-author-attention, breaking-change, changes-requested

#858 test: add logging to summarize failure
  plugins/aladino/actions/robinSummarize.go
Labels: plugins, ship, small, waiting-review, improvements

#853 feat: add repository target to push event
  handler/processors.go
  handler/processors_test.go
Labels: medium, ask, new-feature

#857 feat: consider run field when deciding if workflow will be executed
  engine/exec.go
  engine/exec_test.go
  engine/inline_rules_normalizer.go
  engine/lang.go
  engine/lang_internal_test.go
  engine/loader.go
  engine/loader_test.go
  engine/program_internal_test.go
  engine/testdata/exec/reviewpad_with_combination_run.yml
  engine/testdata/exec/reviewpad_with_multiple_activated_workflows.yml
  engine/testdata/exec/reviewpad_with_single_conditional_run.yml
  engine/testdata/exec/reviewpad_with_skipped_workflow.yml
  integration_test/assets/builtin-close.yml
  integration_test/assets/builtin-delete-head-branch.yml
  integration_test/assets/builtin-fail.yml
  integration_test/assets/builtin-merge.yml
  integration_test/assets/builtin-others.yml
Labels: large, ask, improvements

#862 feat: run robin summarize asynchronously
  lang/aladino/builtins.go
  lang/aladino/env.go
  lang/aladino/exec.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  plugins/aladino/actions/robinSummarize.go
Labels: plugins, ship, large, waiting-approval

#865 fix: push event should find pull requests
  handler/processors.go
  handler/processors_test.go
Labels: ship, small

#868 fix: $assignCodeAuthorReviewers shouldn't assign reviewers when there is already feedback provided
  plugins/aladino/actions/assignCodeAuthorReviewers.go
  plugins/aladino/actions/assignCodeAuthorReviewers_test.go
Labels: plugins, ship, medium

#882 refactor: use go-lib log
  cli/cmd/check.go
  cli/cmd/run.go
  codehost/github/repo_test.go
  go.mod
  go.sum
  handler/processors_test.go
  utils/log.go
Labels: ship, medium

#883 feat(summarize): add request id to error message for tracking
  plugins/aladino/actions/robinSummarize.go
Labels: plugins, ship, small

#884 refactor: tidy runner and remove cookbook
  cookbook/ingredients/label.go
  cookbook/recipes.go
  cookbook/recipes/recipe.go
  cookbook/recipes/size.go
  runner.go
Labels: ship, large, critical

#887 fix: refactor is updated with base branch implementation
  codehost/github/pull_requests.go
  plugins/aladino/functions/isUpdatedWithBaseBranch.go
  plugins/aladino/functions/isUpdatedWithBaseBranch_test.go
Labels: plugins, ship, medium

#876 feat: merge and fail should update check run status
  cli/cmd/run.go
  engine/env.go
  engine/exec_test.go
  integration_test/integration_test.go
  lang/aladino/env.go
  lang/aladino/env_test.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
  lang/aladino/report.go
  plugins/aladino/actions/failCheckStatus.go
  plugins/aladino/actions/merge.go
  plugins/aladino/builtins.go
  runner.go
Labels: plugins, large, critical, ask

#891 feat: stack fail messages along with failCheckStatus messages
  plugins/aladino/actions/fail.go
Labels: plugins, ship, small

#892 fix: cli
  README.md
  cli/cmd/check.go
  cli/cmd/flags.go
  cli/cmd/root.go
  cli/cmd/run.go
  codehost/client.go
Labels: plugins, ship, large

#885 feat: eager evaluation of reviewpad files
  engine/exec.go
  lang/aladino/interpreter.go
  runner.go
Labels: large, critical, ask

#893 chore: upgrade dependencies
  go.mod
  go.sum
Labels: ship, medium

#895 fix: execute extra-actions in run clause
  engine/exec.go
  engine/exec_test.go
  engine/testdata/exec/reviewpad_with_workflow_else.yml
  engine/testdata/exec/reviewpad_with_workflow_extra_actions_then.yml
Labels: ship, large

#896 fix: extra actions exec
  engine/exec.go
  engine/exec_test.go
Labels: ship, medium

#901 feat: support discussion events
  go.mod
  go.sum
  handler/processors.go
Labels: ship, medium, critical

#903 feat: get discussion comments and add-rem reactions
  codehost/github/discussions.go
Labels: ship, large

#904 chore: update qodana.yml
  .github/workflows/qodana.yml
Labels: ship, small

#905 fix(GetDiscussionComments): afterCursor initialization
  codehost/github/discussions.go
  codehost/github/discussions_test.go
Labels: ship, small

#914 fix: PaginatedRequest
  codehost/github/pagination.go
Labels: ship, small

#916 refactor: check if gh merge queue is enabled in a different graphql request
  codehost/github/pull_requests.go
  plugins/aladino/actions/merge.go
  plugins/aladino/actions/merge_test.go
Labels: plugins, large, ask

#917 chore: uncomment unit test
  engine/exec_test.go
Labels: ship, small

#918 fix: ignore pull request author as reviewer
  plugins/aladino/functions/reviewers.go
  plugins/aladino/functions/reviewers_test.go
Labels: plugins, ship, medium

#921 fix: filter reviewpad reviews
  plugins/aladino/actions/assignCodeAuthorReviewers.go
Labels: plugins, ship, small

#911 feat: for each loops
  engine/env.go
  engine/exec.go
  engine/exec_test.go
  engine/inline_rules_normalizer.go
  engine/lang.go
  engine/linter.go
  engine/linter_internal_test.go
  engine/loader.go
  engine/testdata/exec/reviewpad_with_conditional_foreach_workflow.yml
  engine/testdata/exec/reviewpad_with_foreach_workflow.yml
  engine/testdata/exec/reviewpad_with_nested_foreach_workflow.yml
  lang/aladino/env.go
  lang/aladino/eval.go
  lang/aladino/interpreter.go
  lang/aladino/typeinfer.go
  lang/value.go
Labels: large, ask

#925 fix: fix type function of array value
  lang/value.go
Labels: ship, small

#920 feat: download gh repo contents through commit SHA
  codehost/github/repositories.go
  engine/loader.go
  plugins/aladino/semantic/symbols.go
  utils/file.go
Labels: medium, ask

#926 fix: multiple pipelines execution
  engine/exec.go
  engine/exec_test.go
  engine/testdata/exec/reviewpad_with_pipelines.yml
  lang/aladino/parser.go
Labels: ship, large

#927 feat(revert): download gh repo contents through commit SHA
  codehost/github/repositories.go
  engine/loader.go
  plugins/aladino/semantic/symbols.go
  utils/file.go
Labels: ship, medium
