Repository reviewpad/reviewpad, pull requests merged in 2023-08, with the labels that each got.

#1009 feat: add activation field to pad check
  engine/lang.go
Labels: ship, small

#1010 refactor: change label not found log
  plugins/aladino/actions/addLabel.go
  plugins/aladino/actions/removeLabel.go
  plugins/aladino/actions/removeLabels.go
Labels: plugins, ship, small

#1012 fix: incorrect rule lint message
  engine/linter.go
  engine/linter_internal_test.go
Labels: ship, large

#1013 refactor: remove linting workflow log
  engine/linter.go
Labels: ship, small

#1020 Update README.md with new branded banner
  README.md
Labels: ship, external-contribution, small, waiting-approval

#1031 feat: alias built-ins to follow naming conventions
  plugins/aladino/builtins.go
Labels: ship, large

#1032 feat: add hasAnyReviewers built-in
  codehost/github/pull_requests.go
  codehost/github/target/pull_request_target.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/hasAnyReviewers.go
  plugins/aladino/functions/hasAnyReviewers_test.go
Labels: plugins, ship, large

#1033 feat: add has label built-in
  plugins/aladino/builtins.go
  plugins/aladino/functions/hasLabel.go
  plugins/aladino/functions/hasLabel_test.go
Labels: plugins, ship, medium

#1034 feat: add has only approved reviews built-in
  codehost/github/pull_requests.go
  codehost/github/target/pull_request_target.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/hasOnlyApprovedReviews.go
  plugins/aladino/functions/hasOnlyApprovedReviews_test.go
Labels: plugins, ship, large

#1035 feat: add get organization teams built-in
  codehost/github/organization.go
  codehost/github/target/common_target.go
  codehost/target.go
  go.mod
  plugins/aladino/builtins.go
  plugins/aladino/functions/getOrganizationTeams.go
  plugins/aladino/functions/getOrganizationTeams_test.go
  utils/load_test.go
Labels: plugins, ship, large

#1037 feat: add get reviewers built-in
  codehost/github/pull_requests.go
  codehost/github/target/pull_request_target.go
  engine/transform.go
  engine/transform_internal_test.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/getReviewers.go
  plugins/aladino/functions/getReviewers_test.go
  plugins/aladino/functions/hasAnyReviewers.go
Labels: plugins, ship, large

#1039 feat: add get user teams built-in
  codehost/client_test.go
  codehost/github/organization.go
  codehost/github/target/common_target.go
  codehost/target.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/getUserTeams.go
  plugins/aladino/functions/getUserTeams_test.go
Labels: plugins, ship, large

#1018 feat: trigger on check
  cli/cmd/run.go
  engine/env.go
  engine/exec.go
  engine/exec_test.go
  engine/inline_rules_normalizer.go
  engine/lang.go
  engine/loader.go
  integration_test/integration_test.go
  lang/aladino/env.go
  lang/aladino/env_test.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
  lang/type_internal_test.go
  runner.go
Labels: ship, medium, critical, ask, waiting-approval

#1048 fix: add transforms for aliased built-ins
  engine/transform.go
  engine/transform_internal_test.go
Labels: ship, large

#1054 feat: wrap github client round tripper to track requests
  cli/cmd/check.go
  cli/cmd/run.go
  codehost/github/client.go
  engine/mocks.go
  handler/processors.go
  integration_test/integration_test.go
  lang/aladino/env_test.go
  lang/aladino/mocks.go
Labels: ship, large

#1059 feat: rate limit information
  codehost/github/client.go
  codehost/github/client_internal_test.go
  go.mod
  go.sum
Labels: ship, large

#1061 feat: rate limit percentage
  codehost/github/client.go
  codehost/github/client_internal_test.go
Labels: ship, medium

#1062 refactor: treat github api request logging errors as warninig
  codehost/github/client.go
Labels: ship, small

#1063 feat: add label property to pad check
  engine/lang.go
Labels: ship, small

#1066 chore: remove ci base image
  ci/baseimage/Dockerfile
Labels: ship, medium
