Repository reviewpad/reviewpad, pull requests merged in 2023-10, with the labels that each got.

#1093 refactor: remove trigger on check property
  cli/cmd/run.go
  engine/env.go
  engine/exec.go
  engine/exec_test.go
  engine/inline_rules_normalizer.go
  engine/lang.go
  engine/loader.go
  integration_test/integration_test.go
  lang/aladino/env.go
  lang/aladino/env_test.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
  runner.go
Labels: ship, medium, critical

#1094 feat: upgrade dependencies
  go.mod
  go.sum
Labels: large, ask

#1097 feat: remove label property from check
  engine/lang.go
Labels: ship, small

#1103 chore: Update README.md
  README.md
Labels: small, ask, waiting-approval
