Repository reviewpad/reviewpad, pull requests merged in 2023-03, with the labels that each got.

#747 fix: pipelines only run on pull requests
  engine/exec.go
Labels: medium, ask, bug-fix

#739 feat: has any check run completed
  engine/transform.go
  engine/transform_internal_test.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/hasAnyCheckRunCompleted.go
  plugins/aladino/functions/hasAnyCheckRunCompleted_test.go
Labels: plugins, large, ask, waiting-review, new-feature, waiting-checks, waiting-approval

#741 chore: remove api version
  engine/exec.go
  engine/inline_rules_normalizer.go
  engine/lang.go
  engine/lang_internal_test.go
  engine/loader.go
  engine/loader_internal_test.go
  engine/loader_test.go
  engine/normalize.go
  engine/normalize_test.go
  runner.go
Labels: medium, critical, ask, improvements

#749 refactor: remove edition property from reviewpad file
  engine/exec.go
  engine/inline_rules_normalizer.go
  engine/lang.go
  engine/lang_internal_test.go
  engine/loader.go
  engine/loader_internal_test.go
  engine/loader_test.go
  engine/normalize.go
  engine/normalize_test.go
  runner.go
Labels: medium, critical, ask, improvements

#737 feat: select amount of desired assignees in assignAssignees
  engine/transform.go
  engine/transform_internal_test.go
  plugins/aladino/actions/assignAssignees.go
  plugins/aladino/actions/assignAssignees_test.go
  plugins/aladino/actions/assignCodeAuthorReviewers.go
Labels: plugins, large, ask, new-feature

#753 fix: minor lint error
  lang/aladino/expr.go
Labels: ship, small, improvements

#735 fix: make cloning log debug level
  codehost/github/repo.go
Labels: small, ask, waiting-review, improvements

#755 feat: robin integration
  engine/commands/commands.go
  engine/commands/robin.go
  engine/commands/robin_test.go
  go.mod
  go.sum
  plugins/aladino/actions/robin.go
  plugins/aladino/builtins.go
Labels: plugins, large, ask, new-feature

#757 feat: add workflow_ref to action event struct
  handler/types.go
Labels: ship, small, new-feature, waiting-checks

#760 feat: hasCodeWithoutSemanticChanges built-in
  README.md
  codehost/diff.go
  codehost/file.go
  codehost/file_internal_test.go
  engine/transform.go
  engine/transform_internal_test.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/hasAnnotation.go
  plugins/aladino/functions/hasAnnotation_internal_test.go
  plugins/aladino/functions/hasCodeWithoutSemanticChanges.go
  plugins/aladino/semantic/symbols.go
  plugins/aladino/semantic/symbols_test.go
Labels: plugins, large, ask, new-feature

#771 feat: introduce robin client
  .github/workflows/build.yml
  go.mod
  go.sum
  plugins/aladino/actions/robin.go
  plugins/aladino/builtins.go
  plugins/aladino/services/robin.go
Labels: plugins, medium, show, waiting-review, new-feature

#783 feat: add model parameter to robin API calls
  engine/commands/robinPrompt.go
  engine/commands/robinPrompt_test.go
  engine/commands/robinSummarize.go
  engine/commands/robinSummarizeExtended.go
  engine/commands/robinSummarizeExtended_test.go
  engine/commands/robinSummarize_test.go
  engine/commands/robin_test.go
  go.mod
  go.sum
  plugins/aladino/actions/robinPrompt.go
  plugins/aladino/actions/robinSummarize.go
Labels: plugins, ship, medium, waiting-review, new-feature

#789 feat: add event sender
  handler/processors.go
  runner.go
Labels: large, critical, ask, waiting-review, improvements

#802 test: fix codehost client creation in integration tests
  integration_test/integration_test.go
Labels: small, ask, waiting-review, bug-fix

#806 chore: update README.md
  README.md
Labels: ship, small, improvements

#808 fix: update summarize header and error message
  plugins/aladino/actions/robinSummarize.go
Labels: plugins, ship, small, bug-fix
