Repository reviewpad/reviewpad, pull requests merged in 2023-02, with the labels that each got.

#662 feat: add integration tests to build
  .github/workflows/build.yml
  .github/workflows/pull-request-build.yml
  README.md
  integration_test/assets/README.md
  integration_test/integration_test.go
  reviewpad.yml
Labels: medium, run-build, ask, waiting-review

#660 feat: extend config unauthorized err handling
  engine/loader.go
  engine/loader_test.go
Labels: medium, small, run-build, ask, waiting-review

#667 fix: empty reviewpad report
  lang/aladino/interpreter_internal_test.go
  lang/aladino/report.go
  lang/aladino/report_internal_test.go
Labels: small, ask, requires-author-attention

#669 feat: update readme with json schema config
  README.md
Labels: small, ask, waiting-review

#666 feat: separate check for fail built in
  codehost/github/commits.go
  integration_test/integration_test.go
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
Labels: medium, ask, waiting-review

#670 feat: buit-in disable merge
  engine/env.go
  integration_test/integration_test.go
  lang/aladino/env.go
  lang/aladino/interpreter.go
  plugins/aladino/actions/disableMerge.go
  plugins/aladino/builtins.go
  runner.go
Labels: plugins, large, critical, ask, waiting-review

#675 chore: update README.md
  README.md
Labels: ship, small

#684 feat: define git blame
  codehost/github/blame.go
  codehost/github/blame_test.go
  codehost/github/client.go
  engine/mocks.go
  go.mod
  go.sum
  lang/aladino/env_test.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/mocks.go
Labels: large, ask, waiting-review

#687 feat: slice blame
  codehost/github/blame.go
  codehost/github/blame_test.go
Labels: large, ask, waiting-review

#688 fix: delete head branch when branch doesn't exist
  codehost/github/pull_requests.go
  plugins/aladino/actions/deleteHeadBranch.go
  plugins/aladino/actions/deleteHeadBranch_test.go
Labels: plugins, medium, ask, waiting-review

#685 feat: approve built-in
  .github/workflows/pull-request-build.yml
  codehost/github/client.go
  codehost/github/client_test.go
  codehost/github/target/pull_request_target.go
  codehost/github/target/pull_request_target_test.go
  engine/transform.go
  engine/transform_internal_test.go
  plugins/aladino/actions/approve.go
  plugins/aladino/actions/review.go
  plugins/aladino/actions/review_test.go
  plugins/aladino/builtins.go
Labels: plugins, large, ask, waiting-review

#689 feat: compute git blame rank
  codehost/github/blame.go
  codehost/github/blame_test.go
Labels: large, ask, waiting-review

#694 feat: GetOpenPullRequestsAsReviewer method
  codehost/github/pull_requests.go
Labels: medium, large, critical, ask, waiting-review

#702 chore: remove ReviewpadIgnoreCommentAnnotation and its references
  lang/aladino/interpreter.go
  lang/aladino/interpreter_internal_test.go
  lang/aladino/report.go
  lang/aladino/report_internal_test.go
  plugins/aladino/actions/comment.go
  plugins/aladino/actions/commentOnce.go
  plugins/aladino/actions/commentOnce_test.go
  plugins/aladino/actions/comment_test.go
  runner.go
Labels: plugins, medium, critical, ask, waiting-review

#706 feat: is updated with base branch
  codehost/github/pull_requests.go
  plugins/aladino/builtins.go
  plugins/aladino/functions/isUpdatedWithBaseBranch.go
  plugins/aladino/functions/isUpdatedWithBaseBranch_test.go
Labels: plugins, large, ask, waiting-review

#707 feat: add parameter to ignore certain conclusions in have all checks run completed
  engine/transform.go
  engine/transform_internal_test.go
  plugins/aladino/functions/haveAllChecksRunCompleted.go
  plugins/aladino/functions/haveAllChecksRunCompleted_test.go
Labels: plugins, large, ask, waiting-review

#711 feat: remove merge gate
  engine/env.go
  lang/aladino/env.go
  lang/aladino/interpreter.go
  plugins/aladino/actions/disableMerge.go
  plugins/aladino/builtins.go
  runner.go
Labels: plugins, medium, critical, waiting-review

#714 feat: improve random reviewer selection
  plugins/aladino/actions/assignCodeAuthorReviewers.go
  plugins/aladino/actions/assignCodeAuthorReviewers_test.go
Labels: plugins, large, ask, waiting-review

#723 fix: transform expressions for pipeline until
  engine/loader.go
Labels: small, ask, waiting-review

#724 feat: prepare release
  plugins/aladino/actions/review.go
  plugins/aladino/actions/review_test.go
  runner.go
  utils/pr.go
  utils/pr_test.go
Labels: plugins, medium, critical, small, ask, waiting-review

#731 fix: rebase built-in on private repositories
  codehost/github/repo.go
Labels: small, ask, waiting-review, bug-fix

#729 chore: load reviewpad file from gh method
  utils/file.go
Labels: medium, critical, ask, waiting-review, improvements, waiting-checks, waiting-approval

#727 feat: remove from project
  codehost/github/projects.go
  codehost/github/target/issue_target.go
  codehost/github/target/pull_request_target.go
  codehost/target.go
  plugins/aladino/actions/removeFromProject.go
  plugins/aladino/actions/removeFromProject_test.go
  plugins/aladino/builtins.go
Labels: plugins, large, ask, waiting-review
